Traceback (most recent call last):
  File "C:\Users\pamcl\WPy64-31230\python-3.12.3.amd64\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\pamcl\WPy64-31230\python-3.12.3.amd64\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pamcl\WPy64-31230\python-3.12.3.amd64\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pamcl\WPy64-31230\python-3.12.3.amd64\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\pamcl\WPy64-31230\python-3.12.3.amd64\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\pamcl\WPy64-31230\python-3.12.3.amd64\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\pamcl\WPy64-31230\python-3.12.3.amd64\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from edcrop import edcrop
import os
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

wdir = os.path.join(os.getcwd(), 'edcrop')

os.chdir(wdir)

yaml = os.path.join(wdir, 'yaml_files/default.yaml')

edcrop.run_model(yaml=yaml)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[1], line 10[0m
[0;32m      6[0m warnings[38;5;241m.[39msimplefilter(action[38;5;241m=[39m[38;5;124m'[39m[38;5;124mignore[39m[38;5;124m'[39m, category[38;5;241m=[39m[38;5;167;01mFutureWarning[39;00m)
[0;32m      8[0m wdir [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(os[38;5;241m.[39mgetcwd(), [38;5;124m'[39m[38;5;124medcrop[39m[38;5;124m'[39m)
[1;32m---> 10[0m [43mos[49m[38;5;241;43m.[39;49m[43mchdir[49m[43m([49m[43mwdir[49m[43m)[49m
[0;32m     12[0m yaml [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(wdir, [38;5;124m'[39m[38;5;124myaml_files/default.yaml[39m[38;5;124m'[39m)
[0;32m     14[0m edcrop[38;5;241m.[39mrun_model(yaml[38;5;241m=[39myaml)

[1;31mFileNotFoundError[0m: [WinError 2] The system cannot find the file specified: 'C:\\Users\\pamcl\\OneDrive - Danmarks Tekniske Universitet\\Dokumenter\\Projects\\Python\\profiler\\docs\\notebooks\\edcrop'

